// Page text in English and Hindi (the EN / हिं toggle). Didi's answers follow the question's language separately.
export type UiLang = "en" | "hi";

export const STRINGS = {
  en: {
    tag: "Official sources first · Indian passports",
    newChat: "New chat",
    heroTitle: ["Namaste! Ask Didi about ", "visas", "."],
    heroBody:
      "Straight answers for Indian passport holders on tourist and short business trips. Official government pages come first; when they don't cover something, Didi searches the web and tells you so. Every answer shows its sources. You can ask in English, Hindi or Hinglish.",
    examples: [
      "Do I need a visa for Vietnam?",
      "What documents do I need for a UK tourist visa?",
      "Can I attend a conference in Japan on a tourist visa?",
      "How long does a Schengen visa take to process?",
    ],
    coverage: "Destinations I cover",
    placeholder: "Ask a visa or entry question…",
    listening: "Listening…",
    inputLabel: "Ask a visa or entry question",
    askByVoice: "Ask by voice (English)",
    stopListening: "Stop listening",
    send: "Send",
    foot: "Not legal or immigration advice. Always confirm on the official site before you book.",
    checking: "Checking the official sources…",
    readAloud: "Read answer aloud",
    stopReading: "Stop reading aloud",
    notCovered: "Not covered by the official pages I have:",
    conflict: "Official sources disagree:",
    stale: (n: number) => `I couldn't re-check ${n === 1 ? "this source" : "some of these sources"} in the last 14 days. Please verify on the official site.`,
    webNote: "I didn't have this in my stored official pages, so I searched the web. Sources marked “Travel site” aren't official — please confirm on the official site.",
    demoNote: "Demo mode: AI summaries are off, so I'm showing the official text directly.",
    sources: "Sources",
    officialSite: "Official site",
    travelSite: "Travel site",
    found: "Found",
    captured: "Captured",
    lastVerified: "Last verified",
    updatedRecently: "Updated recently",
    checkHere: "Check here:",
    verify: "Rules can change — please confirm on the official site before you book or apply.",
    disclaimerWeb: "Information found on the web, not legal or immigration advice. Rules can change.",
    disclaimerOfficial: "Information from official sources, not legal or immigration advice. Rules can change.",
    micBlocked: "Microphone access was blocked. You can allow it in your browser settings, or just type.",
    offline: "I couldn't reach the server. Check your connection and try again.",
    genericError: "Something went wrong.",
    langSwitch: "Switch to Hindi",
  },
  hi: {
    tag: "पहले आधिकारिक स्रोत · भारतीय पासपोर्ट",
    newChat: "नई चैट",
    heroTitle: ["नमस्ते! दीदी से ", "वीज़ा", " के बारे में पूछिए।"],
    heroBody:
      "टूरिस्ट और छोटी बिज़नेस यात्राओं पर जाने वाले भारतीय पासपोर्ट धारकों के लिए सीधे जवाब। पहले सरकारी वेबसाइटें देखी जाती हैं; जब वहाँ जानकारी नहीं मिलती, तो दीदी वेब पर खोजती है और यह साफ़ बताती है। हर जवाब के साथ स्रोत दिखते हैं। आप हिंदी, Hinglish या अंग्रेज़ी में पूछ सकते हैं।",
    examples: [
      "क्या मुझे वियतनाम के लिए वीज़ा चाहिए?",
      "UK टूरिस्ट वीज़ा के लिए कौन-से दस्तावेज़ चाहिए?",
      "Japan mein conference ke liye tourist visa chalega?",
      "शेंगेन वीज़ा मिलने में कितना समय लगता है?",
    ],
    coverage: "जिन देशों की जानकारी मैं देती हूँ",
    placeholder: "वीज़ा या एंट्री के बारे में पूछिए…",
    listening: "सुन रही हूँ…",
    inputLabel: "वीज़ा या एंट्री के बारे में पूछिए",
    askByVoice: "बोलकर पूछिए (हिंदी)",
    stopListening: "सुनना बंद करें",
    send: "भेजें",
    foot: "यह कानूनी या इमिग्रेशन सलाह नहीं है। बुकिंग से पहले आधिकारिक वेबसाइट पर ज़रूर जाँचें।",
    checking: "आधिकारिक स्रोत देख रही हूँ…",
    readAloud: "जवाब सुनें",
    stopReading: "सुनाना बंद करें",
    notCovered: "मेरे आधिकारिक पेजों में यह नहीं है:",
    conflict: "आधिकारिक स्रोतों में अलग-अलग जानकारी है:",
    stale: (n: number) => `पिछले 14 दिनों में ${n === 1 ? "यह स्रोत" : "इनमें से कुछ स्रोत"} दोबारा जाँचे नहीं जा सके। कृपया आधिकारिक वेबसाइट पर पुष्टि करें।`,
    webNote: "यह जानकारी मेरे सहेजे गए आधिकारिक पेजों में नहीं थी, इसलिए मैंने वेब पर खोजा। “ट्रैवल साइट” वाले स्रोत आधिकारिक नहीं हैं — कृपया आधिकारिक वेबसाइट पर पुष्टि करें।",
    demoNote: "डेमो मोड: AI सारांश बंद हैं, इसलिए आधिकारिक पेज का टेक्स्ट सीधे दिखा रही हूँ।",
    sources: "स्रोत",
    officialSite: "आधिकारिक साइट",
    travelSite: "ट्रैवल साइट",
    found: "मिला",
    captured: "सहेजा",
    lastVerified: "आख़िरी जाँच",
    updatedRecently: "हाल ही में बदला",
    checkHere: "यहाँ देखें:",
    verify: "नियम बदल सकते हैं — बुकिंग या आवेदन से पहले आधिकारिक वेबसाइट पर ज़रूर जाँचें।",
    disclaimerWeb: "वेब पर मिली जानकारी, कानूनी या इमिग्रेशन सलाह नहीं। नियम बदल सकते हैं।",
    disclaimerOfficial: "आधिकारिक स्रोतों से जानकारी, कानूनी या इमिग्रेशन सलाह नहीं। नियम बदल सकते हैं।",
    micBlocked: "माइक्रोफ़ोन की अनुमति नहीं मिली। ब्राउज़र सेटिंग में अनुमति दें, या टाइप करके पूछें।",
    offline: "सर्वर से जुड़ नहीं पाई। इंटरनेट जाँचकर फिर कोशिश करें।",
    genericError: "कुछ गड़बड़ हो गई।",
    langSwitch: "Switch to English",
  },
};

export type Strings = (typeof STRINGS)["en"];
