// Page text in English and Hindi (the EN / हिं toggle). Didi's answers follow the question's language separately.
export type UiLang = "en" | "hi";

export const STRINGS = {
  en: {
    tag: "Official sources first · Indian passports",
    newChat: "New chat",
    kicker: "Namaste, traveller! 👋",
    heroTitle: ["Where are you ", "flying", " next?"],
    examplesLabel: "Try asking",
    thinking: ["Checking embassy pages…", "Asking the immigration desk…", "Reading the fine print…", "Stamping your passport…"],
    heroBody: "Visa answers for Indian passports, straight from official sources. Pick a country or just ask.",
    examples: [
      "Do I need a visa for Vietnam?",
      "What documents do I need for a UK tourist visa?",
      "Can I attend a conference in Japan on a tourist visa?",
      "How long does a Schengen visa take to process?",
    ],
    coverage: "Pick a stamp to start",
    pillQuestion: (name: string) => `Do I need a visa for ${name === "Schengen area" ? "the Schengen area" : name === "UK" || name === "US" || name === "UAE" ? `the ${name}` : name}?`,
    placeholder: "Ask Didi anything…",
    listening: "Listening…",
    inputLabel: "Ask a visa or entry question",
    askByVoice: "Ask by voice (English)",
    stopListening: "Stop listening",
    send: "Send",
    foot: "Not legal or immigration advice. Always confirm on the official site before you book.",
    checking: "Checking the official sources…",
    readAloud: "Read answer aloud",
    stopReading: "Stop reading aloud",
    notCovered: "Not covered by the official pages I have:",
    conflict: "Official sources disagree:",
    stale: (n: number) => `I couldn't re-check ${n === 1 ? "this source" : "some of these sources"} in the last 14 days. Please verify on the official site.`,
    webNote: "Found on the web, not in my official pages. “Travel site” sources aren't official.",
    webExtraTitle: "From the web, for the part above",
    webExtraNote: "This part is from the web. “Travel site” sources aren't official.",
    searchWeb: "Search the web for more",
    searchingWeb: "Searching the web… (about 15 seconds)",
    searchWebHint: "Uses travel sites as well as official ones, and labels which is which.",
    webNothing: "I searched the web too, but couldn't find a reliable answer. Please check the official site.",
    pausedNote: "Didi's written answers are paused for a moment, so here's the relevant official text directly. Please try again a little later for a full answer.",
    demoNote: "Demo mode: AI summaries are off, so I'm showing the official text directly.",
    sources: "Sources",
    officialSite: "Official site",
    travelSite: "Travel site",
    found: "Found",
    captured: "Captured",
    lastVerified: "Last verified",
    updatedRecently: "Updated recently",
    checkHere: "Check here:",
    verify: "Rules can change — please confirm on the official site before you book or apply.",
    footnote: "Rules change — confirm on the official site before you book. Not legal advice.",
    disclaimerWeb: "Information found on the web, not legal or immigration advice. Rules can change.",
    disclaimerOfficial: "Information from official sources, not legal or immigration advice. Rules can change.",
    micBlocked: "Microphone access was blocked. You can allow it in your browser settings, or just type.",
    offline: "I couldn't reach the server. Check your connection and try again.",
    genericError: "Something went wrong.",
    langSwitch: "Switch to Hindi",
  },
  hi: {
    tag: "पहले आधिकारिक स्रोत · भारतीय पासपोर्ट",
    newChat: "नई चैट",
    kicker: "नमस्ते, मुसाफ़िर! 👋",
    heroTitle: ["अगली ", "उड़ान", " कहाँ की है?"],
    examplesLabel: "ऐसे पूछिए",
    thinking: ["दूतावास के पेज देख रही हूँ…", "इमिग्रेशन डेस्क से पूछ रही हूँ…", "बारीक नियम पढ़ रही हूँ…", "पासपोर्ट पर ठप्पा लगा रही हूँ…"],
    heroBody: "भारतीय पासपोर्ट के लिए वीज़ा जवाब, सीधे सरकारी स्रोतों से। कोई देश चुनिए या सीधे पूछिए।",
    examples: [
      "क्या मुझे वियतनाम के लिए वीज़ा चाहिए?",
      "UK टूरिस्ट वीज़ा के लिए कौन-से दस्तावेज़ चाहिए?",
      "Japan mein conference ke liye tourist visa chalega?",
      "शेंगेन वीज़ा मिलने में कितना समय लगता है?",
    ],
    coverage: "शुरू करने के लिए कोई स्टैम्प चुनिए",
    pillQuestion: (name: string) => `क्या मुझे ${name} के लिए वीज़ा चाहिए?`,
    placeholder: "दीदी से कुछ भी पूछिए…",
    listening: "सुन रही हूँ…",
    inputLabel: "वीज़ा या एंट्री के बारे में पूछिए",
    askByVoice: "बोलकर पूछिए (हिंदी)",
    stopListening: "सुनना बंद करें",
    send: "भेजें",
    foot: "यह कानूनी या इमिग्रेशन सलाह नहीं है। बुकिंग से पहले आधिकारिक वेबसाइट पर ज़रूर जाँचें।",
    checking: "आधिकारिक स्रोत देख रही हूँ…",
    readAloud: "जवाब सुनें",
    stopReading: "सुनाना बंद करें",
    notCovered: "मेरे आधिकारिक पेजों में यह नहीं है:",
    conflict: "आधिकारिक स्रोतों में अलग-अलग जानकारी है:",
    stale: (n: number) => `पिछले 14 दिनों में ${n === 1 ? "यह स्रोत" : "इनमें से कुछ स्रोत"} दोबारा जाँचे नहीं जा सके। कृपया आधिकारिक वेबसाइट पर पुष्टि करें।`,
    webNote: "यह वेब से मिला है, मेरे आधिकारिक पेजों से नहीं। “ट्रैवल साइट” वाले स्रोत आधिकारिक नहीं हैं।",
    webExtraTitle: "बाकी जानकारी वेब से",
    webExtraNote: "यह हिस्सा वेब से है। “ट्रैवल साइट” वाले स्रोत आधिकारिक नहीं हैं।",
    searchWeb: "वेब पर और खोजें",
    searchingWeb: "वेब पर खोज रही हूँ… (लगभग 15 सेकंड)",
    searchWebHint: "आधिकारिक के साथ ट्रैवल साइटें भी देखी जाएँगी, और बताया जाएगा कि कौन-सी कौन है।",
    webNothing: "मैंने वेब पर भी खोजा, पर भरोसेमंद जवाब नहीं मिला। कृपया आधिकारिक वेबसाइट देखिए।",
    pausedNote: "दीदी के लिखे जवाब अभी कुछ देर के लिए रुके हैं, इसलिए आधिकारिक पेज का संबंधित टेक्स्ट सीधे दिखा रही हूँ। पूरा जवाब पाने के लिए थोड़ी देर बाद फिर पूछिए।",
    demoNote: "डेमो मोड: AI सारांश बंद हैं, इसलिए आधिकारिक पेज का टेक्स्ट सीधे दिखा रही हूँ।",
    sources: "स्रोत",
    officialSite: "आधिकारिक साइट",
    travelSite: "ट्रैवल साइट",
    found: "मिला",
    captured: "सहेजा",
    lastVerified: "आख़िरी जाँच",
    updatedRecently: "हाल ही में बदला",
    checkHere: "यहाँ देखें:",
    verify: "नियम बदल सकते हैं — बुकिंग या आवेदन से पहले आधिकारिक वेबसाइट पर ज़रूर जाँचें।",
    footnote: "नियम बदलते रहते हैं — बुकिंग से पहले आधिकारिक वेबसाइट पर जाँचें। यह कानूनी सलाह नहीं है।",
    disclaimerWeb: "वेब पर मिली जानकारी, कानूनी या इमिग्रेशन सलाह नहीं। नियम बदल सकते हैं।",
    disclaimerOfficial: "आधिकारिक स्रोतों से जानकारी, कानूनी या इमिग्रेशन सलाह नहीं। नियम बदल सकते हैं।",
    micBlocked: "माइक्रोफ़ोन की अनुमति नहीं मिली। ब्राउज़र सेटिंग में अनुमति दें, या टाइप करके पूछें।",
    offline: "सर्वर से जुड़ नहीं पाई। इंटरनेट जाँचकर फिर कोशिश करें।",
    genericError: "कुछ गड़बड़ हो गई।",
    langSwitch: "Switch to English",
  },
};

export type Strings = (typeof STRINGS)["en"];
